/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as lotTokenSol from "./LotToken.sol";
export type { lotTokenSol };
import type * as tokenFarmSol from "./TokenFarm.sol";
export type { tokenFarmSol };
import type * as libs from "./libs";
export type { libs };
