/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as tokenFarmSol from "./TokenFarm.sol";
export type { tokenFarmSol };
import type * as libs from "./libs";
export type { libs };
export type { LotToken } from "./LotToken";
